name: GunSystemV3
main: at.flori4n.gunsystem.GunSystem
version: 1.0-SNAPSHOT
author: Flori4n
commands:
  creategun:
    description: Create a gun with custom stats
    usage: /creategun <name> <magazineSize> <shootingSpeed> <reloadTime> <damage> <shootingDebounce> <reloadingDebounce>
